//Migrate.h
#define EN_ALPHA_INC 0


#define EN_SWITCH_FONT_MENU 0
#define EN_PAGE_STAMPS 0
#define EN_EDIT_SCROLLBAR 1
#define EN_TIMERS 0
#define EN_THREADEX 0
#define EN_PRINT_DLG 0

#define EN_U_ALPHA_CURSOR_TYPE_VAR 0
#define EN_U_ALPHA_REFRESH_CHAR_PRESET_DISP 0
#define EN_PLAY_IMAGE_HEADER_INFO 0
#define EN_U_ALPHA_ROLL_SPEED 0
#define EN_U_ALPHA_PREVIEW_WINDOW_HANDLE 0
#define EN_U_ALPHA_PLAY_CURSOR 0
#define EN_U_ALPHA_PLAYBACK_WIN 0
#define EN_EFFECTSDIALOG 0
#define EN_UPDATE_FONT_ATTRIBUTES_IN_MENU 0

#define EN_UPDATE_CUR_ATTR_SAMPLE_WINDOW 0
#define EN_PROMPT_FILE_PATHNAME_POPUP 0

#define EN_ACGP_DLL 0

#define EN_U_ALPHA_MAIN_WINDOW_HANDLE 0
#define EN_PICTURE_SIZE_REQUESTER 0
#define EN_OLD_FILE_REQUESTER 0

#define EN_OLD_BINS 0




//DEFINES TO GET BY
#define PRESET_MENU_PICON_WIDTH 40
#define	PRESET_MENU_PICON_HEIGHT 40
