//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cgUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PAGE_EFFECT                 101
#define IDD_COMM_MODEM                  102
#define IDD_PAGE_PRESET                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDP_OLE_INIT_FAILED             105
#define CG_IDD_BOTTOM                   106
#define IDD_ZOOM_BOX                    106
#define CG_ID_VIEW_BOTTOM               107
#define IDD_DLG_CAP_PICONS              108
#define IDD_TITLE_VDO_SETUP             109
#define IDR_MAINFRAME                   128
#define IDD_VIDEO_CLIP_DLG              128
#define IDR_CGUITYPE                    129
#define IDB_PRINTER                     129
#define IDD_VIDEO_FRAME_DLG             129
#define IDD_DLGBAR_BOTTOM               130
#define IDB_FILE_TYPES                  130
#define IDR_KENT_MENU                   130
#define IDB_TABCTRL_IMAGE               131
#define IDD_PAGE_FILTER                 131
#define IDD_PAGE_CAPTURE                132
#define IDD_DLGBAR_LEFT                 133
#define IDD_PAGE_PAGE                   134
#define IDD_PAGE_LAYER                  135
#define IDR_PANEL_BAR                   136
#define IDR_FORMAT_BAR                  136
#define IDD_DLGBAR_BINTOP               138
#define IDD_DLGBAR_PPAL                 139
#define IDD_DLGBAR_PLNE                 140
#define IDD_DLG_PALETTE                 140
#define IDD_DLGBAR_BINBOT               141
#define IDD_DLGBAR_PCIR                 142
#define IDD_DLGBAR_PFBG                 143
#define IDD_DLGBAR_PGRD                 144
#define IDD_PAGE_ATTRIB                 145
#define IDD_PG_FACE                     146
#define IDD_PG_OUTLINE_1                147
#define IDD_PG_OUTLINE_2                148
#define IDD_PG_SHADOW                   149
#define IDD_PG_CAST                     151
#define IDB_ATTRIB_IMAGE                153
#define IDB_UNDERLINE                   154
#define IDB_ITALIC                      155
#define IDB_BOLD                        156
#define IDB_FONT_WIDTH                  157
#define IDB_FONT_HEIGHT                 158
#define IDB_ROTATE                      159
#define IDB_JUST_CTR                    160
#define IDB_V_CENTER                    160
#define IDB_JUST_TOP                    161
#define IDB_PALETTE                     162
#define IDI_BOLD                        173
#define IDI_PALETTE                     174
#define IDI_ITALIC                      175
#define IDI_UNDERLINE                   176
#define IDI_FONT_HEIGHT                 177
#define IDB_JUSTIFY                     178
#define IDB_H_CENTER                    179
#define IDB_JUST_LEFT                   180
#define IDB_JUST_RIGHT                  181
#define IDB_JUST_BOT                    183
#define IDB_GRID                        184
#define IDD_ATTRIB_TEXT                 185
#define IDD_ATTRIB_LINE                 186
#define IDD_ATTRIB_BOX                  187
#define IDD_ATTRIB_OVAL                 188
#define IDD_ATTRIB_FILL                 189
#define IDB_IMAGE_TXGRF                 190
#define IDD_PAGE_SETUP_DLG              190
#define IDR_TEXTGRAPH                   191
#define IDI_ALPHA                       193
#define IDI_SIZE                        195
#define IDI_X_OFFSET                    196
#define IDI_Y_OFFSET                    197
#define IDI_FEATHER                     198
#define IDI_POINTER                     199
#define IDI_IMPORT                      200
#define IDI_LOCK                        201
#define IDI_KERN                        202
#define IDI_SPACE                       203
#define IDI_UNLOCK                      204
#define IDI_UNDERLNE                    205
#define IDI_BACK_MINUS                  208
#define IDI_BACK_GRD                    209
#define IDI_FORE_GRD                    210
#define IDI_FORE_PLUS                   211
#define IDI_FONT_WIDTH                  212
#define IDI_ROTATE                      213
#define IDI_BEVEL                       216
#define IDI_SAVE                        217
#define IDI_OPEN                        218
#define IDI_REDO                        219
#define IDI_UNDO                        220
#define IDD_DLG_MESG                    223
#define IDI_SOLID                       224
#define IDI_TAG_INVERT                  225
#define IDI_TAG_SHIFT                   226
#define IDI_TAG_SPACE                   227
#define IDI_TAG_SUB                     228
#define IDI_V_PERCENT                   229
#define IDI_H_PERCENT                   230
#define IDI_4POINT                      231
#define IDI_CIRCULAR                    232
#define IDI_LINEAR                      233
#define IDI_TAG_ADD                     234
#define IDI_TAG_CLEAR                   235
#define IDD_DLG_SPELL_CHECKER           236
#define IDD_PIC_FILE_DLG                237
#define IDI_SMALLCAP                    240
#define IDD_DLG_ICON_SELECT             241
#define IDD_VM_VDO_SETUP                242
#define IDI_UP_RIGHT                    245
#define IDI_DIR_UP_RIGHT                245
#define IDI_ICON1                       246
#define IDD_TAB_SETUP                   247
#define IDD_DLG_ANNOTATION              248
#define IDD_DLG_PREFER                  249
#define IDI_BROWSE                      252
#define IDD_GET_PATH                    254
#define IDI_DIR_DOWN_LEFT               256
#define IDI_DIR_DOWN_RIGHT              257
#define IDI_DIR_LEFT                    258
#define IDI_DIR_RIGHT                   259
#define IDI_DIR_UP                      260
#define IDI_DIR_UP_LEFT                 261
#define IDI_DIR_DOWN                    262
#define IDI_SUPER_SCRIPT                263
#define IDI_SUB_SCRIPT                  264
#define IDD_DLG_CHAR_MAP                265
#define IDD_FONT_LOCATOR                269
#define IDD_PAGE_BASELINE               275
#define IDI_TYPE_UP                     276
#define IDI_TYPE_AUTO                   279
#define IDI_TYPE_DOWN                   280
#define IDI_TYPE_TO_RIGHT               281
#define IDI_J_TOP                       283
#define IDI_J_CENTER                    284
#define IDI_J_LEFT                      285
#define IDI_J_MIDDLE                    286
#define IDI_J_RIGHT                     287
#define IDD_PIC_LOAD_OPT                288
#define IDI_J_BOTTOM                    288
#define IDD_ATTRIB_IMPORT               289
#define IDI_J_JUSTIFY                   289
#define IDD_COMM_SENDER                 290
#define IDD_COMM_FINDER                 291
#define IDD_COMM_DOWNLOAD               292
#define IDD_COMM_RECEIVER               293
#define IDD_COMM_WAITING                294
#define IDD_MAIN_GAME                   295
#define IDD_MUTLIPLAYER_CONNECT         296
#define IDD_ALPHA_BOX                   297
#define IDI_BL_CIRCLE                   298
#define IDI_BL_CURVE                    299
#define IDI_BL_DEFAULT                  300
#define IDI_BL_ALIGN_BOT                301
#define IDI_BL_ALIGN_TOP                302
#define IDD_PAGE_SELECTION              303
#define IDI_ADVANCE                     304
#define IDI_TT_FONT                     305
#define IDD_TYPE_FACE_OPT               307
#define IDD_PAGE_VIEW                   308
#define IDI_NEW_PAGE                    309
#define IDI_EXPORT_PAGE                 310
#define IDI_MAG_PLUS                    311
#define IDI_MAG_MINUS                   312
#define IDI_MAG_NORMAL                  313
#define IDC_NORMAL                      316
#define IDC_4WAY                        317
#define IDC_RIGHT_LEFT                  318
#define IDC_VERT                        319
#define IDC_LEFT_RIGHT                  320
#define IDC_HORIZ                       321
#define IDD_PAGE_TEMPLATES              322
#define IDC_ROTATE                      324
#define IDR_LITE_TXTGRAF                325
#define IDD_DLG_PROG_SETTING            327
#define IDB_TEST                        328
#define IDD_SEL_EFFECT                  329
#define IDB_64x48                       330
#define IDI_SAVE_STYLE                  331
#define IDR_POP_LAYER_LIST              332
#define IDR_POP_PAGE_LIST               339
#define IDR_POP_PAGE_OPT                340
#define IDR_POP_PG_N_OBJ                341
#define IDR_POP_STYLE_BIN               342
#define IDR_POP_COLOR_BIN               343
#define IDD_ATTRIB_CURVE                344
#define IDD_ATTRIB_POLYGON              345
#define IDI_TEXT_DN                     346
#define IDI_BOX_DN                      347
#define IDI_CURVE                       348
#define IDI_CURVE_DN                    349
#define IDI_ELLIPSE                     350
#define IDI_ELLIPSE_DN                  351
#define IDI_LINE                        352
#define IDI_LINE_DN                     353
#define IDI_POLYGON                     354
#define IDI_POLYGON_DN                  355
#define IDI_TEXT                        356
#define IDI_BOX                         357
#define IDI_OFF_SWITCH                  361
#define IDI_ON_SWITCH                   362
#define IDC_TAB_BOTTOM                  1000
#define IDC_PLAYER_NAME_EDIT            1000
#define IDC_TAB_LEFT                    1001
#define IDC_GAMES_LIST                  1001
#define IDC_TREE                        1001
#define IDC_JOIN                        1002
#define IDC_CREATE                      1003
#define IDC_CONNECTION_LIST             1004
#define IDC_BACK                        1005
#define IDC_FRM_PICON                   1007
#define IDC_VSB_PICON                   1008
#define IDC_ED_PAGE_NUM                 1011
#define IDC_STC_OF                      1012
#define IDC_STC_PAGE_TOTAL              1013
#define IDC_SEARCH_CHECK                1013
#define IDC_STC_PAGE                    1014
#define IDC_STC_TYPE                    1015
#define IDC_CB_PAGE_TYPE                1016
#define IDC_STATIC_NOTE                 1016
#define IDC_STC_EFFECT                  1022
#define IDC_STC_HOLD_TIME               1023
#define IDC_ED_MM                       1024
#define IDC_SPN_MM                      1025
#define IDC_ED_SC                       1026
#define IDC_SPN_SC                      1027
#define IDC_ED_FM                       1028
#define IDC_SPN_FM                      1029
#define IDC_STC                         1030
#define IDC_STC2                        1031
#define IDC_ED_SPD                      1032
#define IDC_SPN_SPEED                   1035
#define IDC_BT_PLAY_PROJ                1036
#define IDC_CK_GPI                      1037
#define IDC_CK_LOOP                     1038
#define IDC_RB_ALL_PAGE                 1039
#define IDC_RB_PAGE                     1040
#define IDC_FRM_CAP_PIC                 1040
#define IDC_ED_START_PG                 1041
#define IDC_BT_EXPORT                   1041
#define IDC_ED_END_PG                   1042
#define IDC_RB_TO_DISK                  1042
#define IDC_STC_TO                      1043
#define IDC_RB_TO_TITLE_PAGE            1043
#define IDC_BT_TAKE                     1044
#define IDC_BT_FADE_VDO                 1045
#define IDC_STC_CAP_TYPE                1045
#define IDC_BT_LIVE_VDO                 1046
#define IDC_CB_CAPTURE_TYPE             1046
#define IDC_STC_SPEED                   1051
#define IDC_TAB_ATTRIB                  1052
#define IDC_CB_FONT                     1053
#define IDC_BT_GRAB                     1053
#define IDC_BT_MULTI_GRAB               1054
#define IDC_ED_WIDTH                    1055
#define IDC_STC_VDO_INPUT               1055
#define IDC_SPN_WIDTH                   1056
#define IDC_VIDEO_OUTPUT_STATIC         1056
#define IDC_ED_HEIGHT                   1057
#define IDC_STC_BRIGHT                  1057
#define IDC_SPN_HEIGHT                  1058
#define IDC_ED_BRIGHT                   1058
#define IDC_RB_BLOD                     1059
#define IDC_SPN_BRIGHT                  1059
#define IDC_RB_ITALIC                   1060
#define IDC_HSD_BRIGHT                  1060
#define IDC_RB_UNDERLINE                1061
#define IDC_STC_CONTRAST                1061
#define IDC_STC_SPACE                   1062
#define IDC_ED_CONSTRAST                1062
#define IDC_ED_SPACE                    1063
#define IDC_SPN_CONSTRAST               1063
#define IDC_SPN_SPACE                   1064
#define IDC_HSD_CONTRAST                1064
#define IDC_STC_H_DELAY                 1065
#define IDC_STC_PRIORITY                1066
#define IDC_ED_HDELAY                   1066
#define IDC_ED_PRIORITY                 1067
#define IDC_SPN_HDELAY                  1067
#define IDC_SPN_PRIORITY                1068
#define IDC_HSD_HDELAY                  1068
#define IDC_CK_FLICKER                  1069
#define IDC_RB_NTSC                     1070
#define IDC_BMP_FONT_WIDTH              1071
#define IDC_RB_PAL                      1071
#define IDC_BT_DEFAULT                  1072
#define IDC_STC_HEIGHT                  1074
#define IDC_STC_BOX                     1077
#define IDC_VSB_PGBOX                   1078
#define IDC_TAB_TXGRA                   1079
#define IDC_VSB_TOPBIN                  1081
#define IDC_VSB_BOTBIN                  1085
#define IDC_LIST_BOX                    1087
#define IDC_LIST_TOP_BIN                1088
#define IDC_LIST_BOT_BIN                1089
#define IDC_STC_FACE_COLOR              1090
#define IDC_STC_FACE_TRANS              1091
#define IDC_BT_COL_IMP_FA               1092
#define IDC_BT_COL_PAL_FA               1093
#define IDC_BT_TRANS_IMP_FA             1094
#define IDC_BT_TRANS_PAL_FA             1095
#define IDC_FRM_COLOR_FA                1096
#define IDC_FRM_TRANS_FA                1097
#define IDC_ED_TRANS_FA                 1098
#define IDC_SPN_TRANS_FA                1099
#define IDC_BT_TRANS_ALPHA_FA           1100
#define IDC_STC_CAST_COLOR              1101
#define IDC_FRM_COLOR_CA                1102
#define IDC_FRM_TRANS_CA                1103
#define IDC_BT_COL_IMP_CA               1104
#define IDC_BT_COL_PAL_CA               1105
#define IDC_BT_COL_IMP_OL               1106
#define IDC_BT_COL_PAL_OL               1107
#define IDC_BT_TRANS_IMP_OL             1108
#define IDC_LOAD_CLIP                   1108
#define IDC_BT_TRANS_PAL_OL             1109
#define IDC_ED_FILE_NAME                1109
#define IDC_BT_TRANS_ALPHA_OL           1110
#define IDC_PLAY_TITLE                  1110
#define IDC_ED_TRANS_OL                 1111
#define IDC_PLAY                        1111
#define IDC_SPN_TRANS_OL                1112
#define IDC_ED_TRANS_OL2                1113
#define IDC_STOP                        1113
#define IDC_BT_TRANS_IMP_OL2            1114
#define IDC_SPN_TRANS_OL2               1115
#define IDC_BT_TRANS_PAL_OL2            1116
#define IDC_BT_TRANS_ALPHA_OL2          1117
#define IDC_VDO_MON                     1117
#define IDC_BT_COL_IMP_OL2              1118
#define IDC_APPLY_TITLE                 1118
#define IDC_BT_COL_PAL_OL2              1119
#define IDC_ED_TRANS_CA                 1120
#define IDC_OUT_FRAME                   1120
#define IDC_SPN_TRANS_CA                1121
#define IDC_STC_SHADOW_COLOR            1122
#define IDC_IN_FRAME                    1122
#define IDC_STC_SHADOW_TRANS            1123
#define IDC_FRM_COLOR_SD                1124
#define IDC_FRM_TRANS_SD                1125
#define IDC_BT_COL_IMP_SD               1126
#define IDC_ED_IN_POINT                 1126
#define IDC_BT_COL_PAL_SD               1127
#define IDC_BT_TRANS_IMP_SD             1128
#define IDC_ED_OUT_POINT                1128
#define IDC_BT_TRANS_PAL_SD             1129
#define IDC_BT_TRANS_ALPHA_SD           1130
#define IDC_HS_IN_POINT                 1130
#define IDC_ED_TRANS_SD                 1131
#define IDC_HS_OUT_POINT                1131
#define IDC_SPN_TRANS_SD                1132
#define IDC_STC_OL2_COLOR               1133
#define IDC_ED_DURATION                 1133
#define IDC_STC_OL2_TRANS               1134
#define IDC_ED_OUT_HH                   1134
#define IDC_FRM_COLOR_OL2               1135
#define IDC_ED_OUT_MM                   1135
#define IDC_FRM_TRANS_OL2               1136
#define IDC_STC_OL_COLOR                1137
#define IDC_ED_OUT_SS                   1137
#define IDC_STC_OL_TRANS                1138
#define IDC_FRM_COLOR_OL                1139
#define IDC_ED_OUT_FF                   1139
#define IDC_FRM_TRANS_OL                1140
#define IDC_ED_IN_HH                    1140
#define IDC_STC_CAST_TRANS              1141
#define IDC_ED_IN_MM                    1141
#define IDC_STC_SD_SIZE                 1142
#define IDC_ED_FR_FF                    1142
#define IDC_ED_IN_SS                    1143
#define IDC_STC_SD_FEATHER              1143
#define IDC_ED_SD_SIZE                  1144
#define IDC_ED_SD_FEATHER               1145
#define IDC_ED_TO_SS                    1145
#define IDC_ED_SD_XOFFSET               1146
#define IDC_ED_SD_YOFFSET               1147
#define IDC_RB_DIRECT_U                 1148
#define IDC_RB_DIRECT_R                 1149
#define IDC_RB_DIRECT_D                 1150
#define IDC_RB_DIRECT_L                 1151
#define IDC_RB_DIRECT_C                 1152
#define IDC_RB_DIRECT_UR                1153
#define IDC_RB_DIRECT_DR                1154
#define IDC_RB_DIRECT_DL                1155
#define IDC_RB_DIRECT_UL                1156
#define IDC_STC_SD_XOFFSET              1157
#define IDC_STC_SD_YOFFSET              1158
#define IDC_SPN_SIZE                    1159
#define IDC_SPN_FEATHER                 1160
#define IDC_SPN_X_OFFSET                1161
#define IDC_SPN_Y_OFFSET                1162
#define IDC_ED_IN_FF                    1162
#define IDC_STC_CA_SIZE                 1163
#define IDC_CB_IN_FORMAT                1163
#define IDC_ED_CA_SIZE                  1164
#define IDC_STC_CA_FEATHER              1165
#define IDC_ED_CA_FEATHER               1166
#define IDC_ED_CA_XOFFSET               1167
#define IDC_ED_CA_YOFFSET               1168
#define IDC_CB_OUT_FORMAT               1168
#define IDC_STC_CA_XOFFSET              1169
#define IDC_STC_CA_YOFFSET              1170
#define IDC_OUT_RECT                    1170
#define IDC_SPN_CA_FEATHER              1171
#define IDC_SPN_CA_SIZE                 1172
#define IDC_SPN_CA_X_OFFSET             1173
#define IDC_ED_TO_HH                    1173
#define IDC_SPN_CA_Y_OFFSET             1174
#define IDC_ED_TO_MM                    1174
#define IDC_RB_CA_DIRECT_UR             1175
#define IDC_RB_CA_DIRECT_U              1176
#define IDC_RB_CA_DIRECT_UL             1177
#define IDC_RB_CA_DIRECT_R              1178
#define IDC_RB_CA_DIRECT_C              1179
#define IDC_RB_CA_DIRECT_L              1180
#define IDC_RB_CA_DIRECT_DL             1181
#define IDC_RB_CA_DIRECT_D              1182
#define IDC_RB_CA_DIRECT_DR             1183
#define IDC_IN_RECT                     1183
#define IDC_STC_MODE                    1184
#define IDC_STC_OL1_SIZE                1184
#define IDC_STC_OL1_FEATHER             1185
#define IDC_STC_GPIPORT                 1185
#define IDC_ED_OL1_SIZE                 1186
#define IDC_ED_OL1_FEATHER              1187
#define IDC_SPN_OL1_SIZE                1188
#define IDC_CB_OUT_MODE                 1188
#define IDC_SPN_OL1_FEATHER             1189
#define IDC_ED_OL1_XOFFSET              1190
#define IDC_ED_TO_FF                    1190
#define IDC_ED_OL1_YOFFSET              1191
#define IDC_CB_OUT_GPIPORT              1191
#define IDC_STC_OL1_XOFFSET             1192
#define IDC_STC_OL1_YOFFSET             1193
#define IDC_SPN_OL1_X_OFFSET            1194
#define IDC_ED_FR_HH                    1194
#define IDC_SPN_OL1_Y_OFFSET            1195
#define IDC_STC_OL2_SIZE                1196
#define IDC_ED_FR_MM                    1196
#define IDC_STC_OL2_FEATHER             1197
#define IDC_ED_OL2_SIZE                 1198
#define IDC_ED_OL2_FEATHER              1199
#define IDC_SPN_OL2_SIZE                1200
#define IDC_ED_FR_SS                    1200
#define IDC_SPN_OL2_FEATHER             1201
#define IDC_STC_OL2_XOFFSET             1202
#define IDC_STC_OL2_YOFFSET             1203
#define IDC_ED_OL2_XOFFSET              1204
#define IDC_ED_OL2_YOFFSET              1205
#define IDC_SPN_OL2_X_OFFSET            1206
#define IDC_SPN_OL2_Y_OFFSET            1207
#define IDC_STC_FA_FEATHER              1208
#define IDC_ED_FA_FEATHER               1209
#define IDC_SPN_FA_FEATHER              1210
#define IDC_STC_WIDTH                   1221
#define IDC_BT_TRANS_IMP_CA             1228
#define IDC_BT_TRANS_PAL_CA             1229
#define IDC_BT_TRANS_ALPHA_CA           1230
#define IDC_CB_TYPE                     1231
#define IDC_SPN_PS_STA                  1232
#define IDC_SPN_PS_HORI                 1233
#define IDC_CB_T_FONT                   1233
#define IDC_SPN_PS_VERT                 1234
#define IDC_FRM_T_PREVIEW               1234
#define IDC_SPN_PS_TOP                  1235
#define IDC_BT_T_LOCK                   1235
#define IDC_SPN_PS_LEFT                 1236
#define IDC_BT_T_F                      1236
#define IDC_SPN_PS_RIGHT                1237
#define IDC_BT_T_PLUS                   1237
#define IDC_SPN_PS_BOTTOM               1238
#define IDC_BT_T_MINUS                  1238
#define IDC_SPN_PS_TAB1                 1239
#define IDC_BT_T_B                      1239
#define IDC_SPN_PS_TAB2                 1240
#define IDC_ED_T_PRIORITY               1240
#define IDC_SPN_PS_TAB3                 1241
#define IDC_SPN_T_PRIORITY              1241
#define IDC_SPN_PS_TAB4                 1242
#define IDC_ED_T_Y                      1242
#define IDC_SPN_PS_TAB5                 1243
#define IDC_ED_T_X                      1243
#define IDC_SPN_PS_TAB6                 1244
#define IDC_ED_T_ROTATION               1244
#define IDC_SPN_PS_TAB7                 1245
#define IDC_ED_T_BEVEL                  1245
#define IDC_SPN_PS_TAB8                 1246
#define IDC_ED_T_SPACE                  1246
#define IDC_SPN_PS_HORI_SPACE           1247
#define IDC_ED_T_KERNING                1247
#define IDC_SPN_PS_VERT_SPACE           1248
#define IDC_ED_T_HEIGHT                 1248
#define IDC_SPN_PS_HORI_OFFSET          1249
#define IDC_ED_T_WIDTH                  1249
#define IDC_SPN_PS_VERT_OFFSET          1250
#define IDC_RB_T_UNDERLNE               1250
#define IDC_SPN_PS_RES_WIDTH            1251
#define IDC_RB_T_ITALIC                 1251
#define IDC_SPN_PS_RES_HEIGHT           1252
#define IDC_RB_T_BOLD                   1252
#define IDC_SPN_T_HEIGHT                1253
#define IDC_SPN_T_SPACING               1254
#define IDC_SPN_T_ROTATE                1255
#define IDC_SPN_T_X                     1256
#define IDC_SPN_T_Y                     1257
#define IDC_SPN_T_BEVEL                 1258
#define IDC_SPN_T_WIDTH                 1259
#define IDC_SPN_T_KERN                  1260
#define IDC_STC_T_HEIGHT                1261
#define IDC_STC_T_SPACE                 1262
#define IDC_STC_T_ROTATION              1263
#define IDC_STC_T_X                     1264
#define IDC_STC_T_Y                     1265
#define IDC_STC_T_BEVEL                 1266
#define IDC_STC_T_KERNING               1267
#define IDC_STC_T_WIDTH                 1268
#define IDC_BT_FONT_LIST                1269
#define IDC_RB_T_SMALL_CAP              1270
#define IDC_BT_PAL_OPEN                 1271
#define IDC_BT_ADVANCE                  1271
#define IDC_BT_PAL_SAVE                 1272
#define IDC_BT_SAVE_STYLE               1272
#define IDC_BT_PAL_REDO                 1273
#define IDC_BT_PAL_UNDO                 1274
#define IDC_STC_CUR_COLOR               1275
#define IDC_STC_BASE_COLOR              1276
#define IDC_BT_PAL_SOLID                1277
#define IDC_BT_PAL_LINEAR               1278
#define IDC_BT_PAL_CIRCULAR             1279
#define IDC_BT_PAL_4POINT               1280
#define IDC_PAL_CUR_COLOR               1281
#define IDC_BT_PAL_COPY                 1282
#define IDC_BT_PAL_SWAP                 1283
#define IDC_SPREAD_COLOR                1284
#define IDC_BT_PAL_ADD                  1286
#define IDC_BT_PAL_DELETE               1287
#define IDC_BT_PAL_CLEAR                1288
#define IDC_BT_PAL_SPACE                1289
#define IDC_BT_PAL_SHIFT                1290
#define IDC_BT_PAL_INVERT               1291
#define IDC_STC_ROTATE                  1292
#define IDC_HSB_ROTATE                  1293
#define IDC_ED_ROTATE                   1294
#define IDC_FRM_BASE_COLOR              1295
#define IDC_VDO_SAFE                    1296
#define IDC_RB_RGB                      1297
#define IDC_RB_HSV                      1298
#define IDC_STC_R                       1299
#define IDC_STC_G                       1300
#define IDC_STC_B                       1301
#define IDC_ED_R                        1302
#define IDC_ED_G                        1303
#define IDC_ED_B                        1304
#define IDC_HSB_R                       1305
#define IDC_HSB_G                       1306
#define IDC_HSB_B                       1307
#define IDC_LIST_PAL_BIN                1309
#define IDC_LIST_TAG                    1317
#define IDC_STC_MSG1                    1318
#define IDC_STC_MSG2                    1319
#define IDC_ED_ROUNDNESS                1320
#define IDC_STC_FILE_NAME               1321
#define IDC_STC_MSG3                    1322
#define IDC_SPN_ED_WIN                  1323
#define IDC_ED_O_ROUNDNESS              1324
#define IDC_ED_H_PERCENT                1324
#define IDC_ED_WIDTH_PERCENT            1324
#define IDC_ED_V_PERCENT                1325
#define IDC_STC_ROUNDNESS               1326
#define IDC_STC_H_PERCENT               1327
#define IDC_STC_V_PERCENT               1328
#define IDC_ED_G_HEIGHT                 1329
#define IDC_ED_G_WIDTH                  1330
#define IDC_ED_G_BEVEL                  1331
#define IDC_ED_G_ROTATION               1332
#define IDC_ED_G_X                      1333
#define IDC_ED_G_Y                      1334
#define IDC_ED_G_PRIORITY               1335
#define IDC_STC_G_WIDTH                 1336
#define IDC_STC_G_BEVEL                 1337
#define IDC_STC_G_Y                     1338
#define IDC_STC_G_X                     1339
#define IDC_STC_G_ROTATION              1340
#define IDC_STC_G_HEIGHT                1341
#define IDC_FRM_G_PREVIEW               1342
#define IDC_BT_G_LOCK                   1343
#define IDC_BT_G_F                      1344
#define IDC_BT_G_PLUS                   1345
#define IDC_BT_G_MINUS                  1346
#define IDC_BT_G_B                      1347
#define IDC_SPN_G_HEIGHT                1348
#define IDC_SPN_ROUNDNESS               1349
#define IDC_SPN_H_PERCENT               1349
#define IDC_SPN_WIDTH_PERCENT           1349
#define IDC_SPN_G_ROTATE                1350
#define IDC_SPN_G_X                     1351
#define IDC_SPN_G_WIDTH                 1352
#define IDC_SPN_V_PERCENT               1353
#define IDC_SPN_G_BEVEL                 1354
#define IDC_SPN_G_Y                     1355
#define IDC_SPN_G_PRIORITY              1356
#define IDC_STC_B_HEIGHT                1357
#define IDC_ED_B_HEIGHT                 1358
#define IDC_STC_B_WIDTH                 1359
#define IDC_ED_B_WIDTH                  1360
#define IDC_SPN_B_HEIGHT                1361
#define IDC_SPN_B_WIDTH                 1362
#define IDC_STC_B_ROTATION              1363
#define IDC_ED_B_ROTATION               1364
#define IDC_STC_B_BEVEL                 1365
#define IDC_ED_B_BEVEL                  1366
#define IDC_SPN_B_ROTATE                1367
#define IDC_SPN_B_BEVEL                 1368
#define IDC_STC_B_X                     1369
#define IDC_ED_B_X                      1370
#define IDC_STC_B_Y                     1371
#define IDC_ED_B_Y                      1372
#define IDC_SPN_B_Y                     1373
#define IDC_SPN_B_X                     1374
#define IDC_ED_B_PRIORITY               1375
#define IDC_SPN_B_PRIORITY              1376
#define IDC_BT_B_B                      1377
#define IDC_BT_B_MINUS                  1378
#define IDC_BT_B_PLUS                   1379
#define IDC_BT_B_F                      1380
#define IDC_BT_B_LOCK                   1381
#define IDC_FRM_B_PREVIEW               1382
#define IDC_FRM_L_PREVIEW               1387
#define IDC_BT_L_LOCK                   1388
#define IDC_BT_L_F                      1389
#define IDC_BT_L_PLUS                   1390
#define IDC_BT_L_MINUS                  1391
#define IDC_BT_L_B                      1392
#define IDC_STC_L_LENGTH                1393
#define IDC_ED_L_LENGTH                 1394
#define IDC_ED_L_THICK                  1395
#define IDC_STC_L_THICK                 1396
#define IDC_SPN_L_THICK                 1397
#define IDC_STC_L_ROTATION              1398
#define IDC_ED_L_ROTATION               1399
#define IDC_STC_L_BEVEL                 1400
#define IDC_ED_L_BEVEL                  1401
#define IDC_SPN_L_ROTATE                1402
#define IDC_SPN_L_BEVEL                 1403
#define IDC_STC_L_X                     1404
#define IDC_ED_L_X                      1405
#define IDC_SPN_L_X                     1406
#define IDC_STC_L_Y                     1407
#define IDC_ED_L_Y                      1408
#define IDC_SPN_L_Y                     1409
#define IDC_ED_L_PRIORITY               1410
#define IDC_SPN_L_PRIORITY              1411
#define IDC_FRM_F_PREVIEW               1412
#define IDC_BT_F_LOCK                   1413
#define IDC_BT_F_F                      1414
#define IDC_BT_F_PLUS                   1415
#define IDC_BT_F_MINUS                  1416
#define IDC_BT_F_B                      1417
#define IDC_ED_F_PRIORITY               1418
#define IDC_SPN_F_PRIORITY              1419
#define IDC_ED_F_Y                      1420
#define IDC_ED_F_X                      1421
#define IDC_STC_F_X                     1422
#define IDC_SPN_F_X                     1423
#define IDC_STC_F_Y                     1424
#define IDC_SPN_F_Y                     1425
#define IDC_SPN_F_BEVEL                 1426
#define IDC_ED_F_BEVEL                  1427
#define IDC_STC_F_BEVEL                 1428
#define IDC_ED_F_ROTATION               1429
#define IDC_STC_F_ROTATION              1430
#define IDC_SPN_F_ROTATE                1431
#define IDC_SPN_F_WIDTH                 1432
#define IDC_ED_F_WIDTH                  1433
#define IDC_STC_F_WIDTH                 1434
#define IDC_SPN_F_HEIGHT                1435
#define IDC_ED_F_HEIGHT                 1436
#define IDC_STC_F_HEIGHT                1437
#define IDC_FRM_O_PREVIEW               1438
#define IDC_BT_O_LOCK                   1439
#define IDC_BT_O_F                      1440
#define IDC_BT_O_PLUS                   1441
#define IDC_BT_O_MINUS                  1442
#define IDC_BT_O_B                      1443
#define IDC_ED_O_PRIORITY               1444
#define IDC_SPN_O_Y                     1445
#define IDC_SPN_O_PRIORITY              1446
#define IDC_ED_O_Y                      1447
#define IDC_STC_O_Y                     1448
#define IDC_SPN_O_X                     1449
#define IDC_ED_O_X                      1450
#define IDC_STC_O_X                     1451
#define IDC_ED_O_BEVEL                  1452
#define IDC_SPN_O_BEVEL                 1453
#define IDC_STC_O_BEVEL                 1454
#define IDC_ED_O_ROTATION               1455
#define IDC_STC_O_ROTATION              1456
#define IDC_SPN_O_ROTATE                1457
#define IDC_SPN_O_WIDTH                 1458
#define IDC_ED_O_WIDTH                  1459
#define IDC_STC_O_WIDTH                 1460
#define IDC_SPN_O_HEIGHT                1461
#define IDC_SPN_O_SIZE                  1461
#define IDC_ED_O_SIZE                   1462
#define IDC_STC_O_SIZE                  1463
#define IDC_SPN_L_LENGTH                1466
#define IDC_CK_PRESERVE_ASPECT          1467
#define IDC_STC_ORIGINAL_WORD           1468
#define IDC_ED_ORIGINAL_WORD            1469
#define IDC_STC_CHANGE_TO               1470
#define IDC_ED_CHANGE_TO                1471
#define IDC_BT_REPLACE                  1472
#define IDC_BT_IGNORE                   1473
#define IDC_BT_ADD                      1474
#define IDC_STC_ALTER_SPELL             1475
#define IDC_LB_ALTER_SPELL              1476
#define IDC_STC_DONE_MSG                1477
#define IDC_PIC_FRAME                   1478
#define IDC_STC_NAME                    1479
#define IDC_STC_LAST_TIME               1480
#define IDC_STC_RES                     1481
#define IDC_STC_OUT_NAME                1482
#define IDC_STC_OUT_TIME                1483
#define IDC_STC_FORMAT                  1483
#define IDC_STC_OUT_RES                 1484
#define IDC_STC_LAST_DATE               1485
#define IDC_STC_OUT_DATE                1486
#define IDC_OK                          1489
#define IDC_STC_SELECT                  1491
#define IDC_RB_SELECT_ALL               1492
#define IDC_RB_SELECT_GFX               1493
#define IDC_RB_SELECT_TEXT              1494
#define IDC_RB_SELECT_CLEAR             1495
#define IDC_MOVE_LEFT                   1496
#define IDC_MOVE_RIGHT                  1497
#define IDC_RB_SELECT                   1499
#define IDC_RB_UNSELECT                 1500
#define IDC_STC_VDO_OVERLAY             1509
#define IDC_CB_VDO_OVERLAY              1510
#define IDC_STC_VDO_PREVIEW             1511
#define IDC_CB_VDO_PREVIEW              1512
#define IDC_CK_VDO_DEFRINGE             1513
#define IDC_CK_ANTI_FLICKER             1514
#define IDC_RB_TAB1                     1515
#define IDC_RB_TAB2                     1516
#define IDC_RB_TAB3                     1517
#define IDC_RB_TAB4                     1518
#define IDC_RB_TAB5                     1519
#define IDC_RB_TAB6                     1520
#define IDC_RB_TAB7                     1521
#define IDC_RB_TAB8                     1522
#define IDC_RB_TAB9                     1523
#define IDC_RB_TAB10                    1524
#define IDC_STC_POSITION                1525
#define IDC_STC_ALIGN                   1526
#define IDC_RB_ALIGN_LEFT               1527
#define IDC_RB_ALIGN_CENTER             1528
#define IDC_RB_ALIGN_RIGHT              1529
#define IDC_RB_ALIGN_DECIMAL            1530
#define IDC_ED_POS                      1531
#define IDC_SPN_POS                     1532
#define IDC_BT_RESET                    1533
#define IDC_ED_ANNOT                    1534
#define IDC_STC_FOLDER                  1535
#define IDC_STC_PROJECT                 1536
#define IDC_STC_GRAPHIC                 1537
#define IDC_STC_PAGE_EXP                1538
#define IDC_ED_PROJ                     1539
#define IDC_ED_GRAF                     1540
#define IDC_ED_PG_EXPORT                1541
#define IDC_BT_BROWSE1                  1542
#define IDC_BT_BROWSE2                  1543
#define IDC_GP_PAGE_TYPE                1544
#define IDC_BT_BROWSE3                  1545
#define IDC_GP_MARGIN                   1546
#define IDC_GP_PAGE_CENTER_OFFSET       1547
#define IDC_GP_SET_TAB                  1548
#define IDC_GP_GRIDS                    1549
#define IDC_GP_RESOLUTION               1550
#define IDC_BT_SUPERSCRIPT              1551
#define IDC_BT_SUBSCRIPT                1552
#define IDC_LIST_CHAR_MAP               1553
#define IDC_SB_CHAR_MAP                 1554
#define IDC_STC_1                       1555
#define IDC_BT_BACKSPACE                1556
#define IDC_STC_2                       1557
#define IDC_BT_DELETE                   1558
#define IDC_STC_3                       1559
#define IDC_BT_ENTER                    1560
#define IDC_STC_4                       1561
#define IDC_BT_LEFT                     1562
#define IDC_BT_RIGHT                    1563
#define IDC_STC_5                       1564
#define IDC_BT_UP                       1565
#define IDC_STC_6                       1566
#define IDC_BT_DOWN                     1567
#define IDC_STC_VIEW                    1568
#define IDC_STC_7                       1569
#define IDC_CK_SERIF_FONT               1570
#define IDC_STC_8                       1571
#define IDC_CK_SANS_SERIF_FONT          1572
#define IDC_STC_SAFE_AREA               1573
#define IDC_CK_SYMBOL_FONT              1574
#define IDC_STC_HORI                    1575
#define IDC_VSB_FONT                    1576
#define IDC_STC_VERT                    1577
#define IDC_FRM_FONT                    1578
#define IDC_STC_LEFT                    1579
#define IDC_GP_BASELINE                 1580
#define IDC_STC_RIGHT                   1581
#define IDC_RB_LINE                     1582
#define IDC_STC_TOP                     1583
#define IDC_RB_CURVE                    1584
#define IDC_STC_BOTTOM                  1585
#define IDC_RB_CIRCLE                   1586
#define IDC_STC_PERCENT                 1587
#define IDC_GP_JUSTIFIY                 1588
#define IDC_STC_SPACING                 1589
#define IDC_RB_LEFT                     1590
#define IDC_STC_PERCENT8                1591
#define IDC_STC_PERCENT2                1592
#define IDC_RB_CENTER                   1593
#define IDC_STC_PERCENT3                1594
#define IDC_RB_RIGHT                    1595
#define IDC_STC_OFFSET                  1596
#define IDC_RB_JUSTIFY                  1597
#define IDC_STC_PERCENT9                1598
#define IDC_ED_TAB1                     1599
#define IDC_STC_PERCENT4                1600
#define IDC_GP_TYPING_DIR               1601
#define IDC_ED_TAB2                     1602
#define IDC_STC_PERCENT5                1603
#define IDC_RB_AUTO                     1604
#define IDC_ED_TAB3                     1605
#define IDC_STC_PERCENT6                1606
#define IDC_RB_TOP_RIGHT                1607
#define IDC_STC_PERCENT7                1608
#define IDC_RB_BOTTOM_UP                1609
#define IDC_ED_TAB4                     1610
#define IDC_RB_TOP_DOWN                 1611
#define IDC_ED_TAB5                     1612
#define IDC_ED_X                        1613
#define IDC_ED_TAB6                     1614
#define IDC_SPN_X                       1615
#define IDC_ED_TAB7                     1617
#define IDC_ED_Y                        1618
#define IDC_ED_TAB8                     1619
#define IDC_SPN_Y                       1620
#define IDC_ED_HORI                     1621
#define IDC_STC_ROTATION                1622
#define IDC_ED_VERT                     1623
#define IDC_ED_ROTATION                 1624
#define IDC_ED_STA                      1625
#define IDC_SPN_ROTATION                1626
#define IDC_ED_LEFT                     1627
#define IDC_STC_LINE_SPACE              1628
#define IDC_ED_TOP                      1629
#define IDC_STC_CHAR_SPACE              1630
#define IDC_ED_RIGHT                    1631
#define IDC_ED_LNE_SPACE                1632
#define IDC_ED_BOTTOM                   1633
#define IDC_SPN_LNE_SPACE               1634
#define IDC_ED_HORI_SPACE               1635
#define IDC_ED_VERT_SPACE               1636
#define IDC_ED_SP_WIDTH                 1637
#define IDC_GP_LINE_MARGIN              1638
#define IDC_ED_SP_HEIGHT                1639
#define IDC_STC_MARGIN_LEFT             1640
#define IDC_ED_HORI_OFFSET              1641
#define IDC_STC_MARGIN_RIGHT            1642
#define IDC_ED_VERT_OFFSET              1643
#define IDC_ED_MARGIN_LEFT              1644
#define IDC_CB_RESOLUTION               1645
#define IDC_SPN_MARGIN_LEFT             1646
#define IDC_ED_MARGIN_RIGHT             1647
#define IDC_BT_STA                      1648
#define IDC_SPN_MARGIN_RIGHT            1649
#define IDC_BT_PM                       1650
#define IDC_CHK_CONSTRAIN               1651
#define IDC_BT_ST                       1652
#define IDC_BT_CHAR_PLUS                1653
#define IDC_BT_GRID                     1654
#define IDC_BT_CHAR_MINUS               1655
#define IDC_GP_CURVE_CTRL               1656
#define IDC_CK_SAFE_TITLE_INDICATOR     1657
#define IDC_GP_CIRCLE_CTRL              1658
#define IDC_CK_HORI                     1659
#define IDC_STC_CURVE_POINT             1660
#define IDC_CK_VERT                     1661
#define IDC_STC_CIR_RADIUS              1662
#define IDC_CK_SHOW_GRIDS               1663
#define IDC_STC_CIR_ASPECT              1664
#define IDC_CK_SNAP_GRID                1665
#define IDC_STC_ALIGN_CIR               1666
#define IDC_CK_SAFE_ACTION              1667
#define IDC_ED_CURVE_CTRL               1668
#define IDC_CK_CENTER_POINT             1669
#define IDC_SPN_CURVE_CTRL              1670
#define IDC_ED_CIR_RADIUS               1671
#define IDC_SPN_RADIUS                  1672
#define IDC_ED_CIR_ASPECT               1673
#define IDC_STC_FILE                    1674
#define IDC_SPN_ASPECT                  1675
#define IDC_STC_ORIG_SIZE               1676
#define IDC_RB_OUT                      1677
#define IDC_STC_X                       1678
#define IDC_STC_ED_WIN_SIZE             1679
#define IDC_STC_Y                       1680
#define IDC_GP_LD_SIZE                  1681
#define IDC_GP_POSITION                 1682
#define IDC_RB_IN                       1683
#define IDC_RB_ORIG_SIZE                1684
#define IDC_RB_FIT_ED_WIN               1685
#define IDC_RB_ED_WIN_SIZE              1686
#define IDC_RB_UL                       1687
#define IDC_RB_UM                       1688
#define IDC_RB_UR                       1689
#define IDC_RB_ML                       1690
#define IDC_RB_CC                       1691
#define IDC_RB_MR                       1692
#define IDC_RB_BL                       1693
#define IDC_RB_BM                       1694
#define IDC_RB_BR                       1695
#define IDC_GP_OBJECT                   1696
#define IDC_FRM_SELECT_OBJ              1697
#define IDC_BT_PREV                     1698
#define IDC_BT_NEXT                     1699
#define IDC_CK_SELECT                   1700
#define IDC_BT_SEL_ALL                  1701
#define IDC_BT_SEL_TEXT                 1702
#define IDC_CK_A_CH_INCLUDE             1703
#define IDC_BT_SEL_GRAPHIC              1704
#define IDC_CK_A_CH_INVERT              1705
#define IDC_BT_UN_SEL_ALL               1706
#define IDC_CK_BLACK_TRIM               1707
#define IDC_GP_VIEW                     1708
#define IDC_STC_FILE_ORIG_SIZE          1709
#define IDC_CK_HIDE_SEL_OBJ             1710
#define IDC_ED_ED_WIN_SIZE              1711
#define IDC_CK_HIDE_TEXT_OBJ            1712
#define IDC_STC_MSG                     1713
#define IDC_ED_HORI_RES                 1714
#define IDC_CK_HIDE_GRAPHIC_OBJ         1715
#define IDC_STC_FRAME                   1716
#define IDC_ED_VERT_RES                 1717
#define IDC_CK_HIDE_LAYER_OBJ           1718
#define IDC_STC_SIZE                    1719
#define IDC_CB_TCP_PORT                 1720
#define IDC_GP_PORT_NUM                 1721
#define IDC_GP_MACH_FINDER              1722
#define IDC_RB_HOSTNAME                 1723
#define IDC_RB_IP_ADDR                  1724
#define IDC_ED_HOSTNAME                 1725
#define IDC_ED_IP_ADDR                  1726
#define IDC_STC_DISP_HOST               1727
#define IDC_BT_FIND                     1728
#define IDC_GP_CONNECT                  1729
#define IDC_STC_HOST_ID                 1730
#define IDC_ED_HOST_ID                  1731
#define IDC_CK_SEL_BOX                  1731
#define IDC_STC_TCP_PORT                1732
#define IDC_BT_TAB                      1732
#define IDC_CB_PORT_NUM                 1733
#define IDC_CK_TAB                      1733
#define IDC_BT_SEND                     1734
#define IDC_CK_GRIDS                    1734
#define IDC_ED_MSG                      1735
#define IDC_CK_LNE_MARGIN               1735
#define IDC_GP_MSG                      1736
#define IDC_CK_BASELINE                 1736
#define IDC_GP_R_MESG                   1737
#define IDC_BT_SETTING                  1737
#define IDC_ED_R_MSG                    1738
#define IDC_GP_PAGE_VIEW                1738
#define IDC_BT_R_SEND                   1739
#define IDC_CK_ASPECT_CORRECTION        1739
#define IDC_GP_HTTP                     1740
#define IDC_CK_SHOW_A_CHANNEL           1740
#define IDC_ED_HTTP                     1741
#define IDC_CK_MONITOR_GAMMA            1741
#define IDC_ED_SHOW_HTML                1742
#define IDC_EDMON_GARMMA                1742
#define IDC_BT_HTTP_GET                 1743
#define IDC_SPN_MON_GAMMA               1743
#define IDC_BT_FTP_GET                  1744
#define IDC_CK_LOCK_POS                 1744
#define IDC_GP_FTP                      1745
#define IDC_ED_FTP                      1746
#define IDC_BT_FILE_GET                 1747
#define IDC_GP_FILE                     1748
#define IDC_ED_FILE                     1749
#define IDC_LC_TEMPLATE                 1749
#define IDC_CK_CERN                     1750
#define IDC_VSB_VERT                    1750
#define IDC_RB_HTML                     1751
#define IDC_BT_SAVE_TEMPLATE            1751
#define IDC_RB_IMAGE                    1752
#define IDC_BT_NEW_LAYER                1752
#define IDC_STC_USERNAME                1753
#define IDC_BT_MOVE_UP                  1753
#define IDC_STC_PASSWORD                1754
#define IDC_BT_MOVE_DOWN                1754
#define IDC_ED_USERNAME                 1755
#define IDC_BT_COPY_LAYER               1755
#define IDC_ED_PASSWORD                 1756
#define IDC_BT_DEL_LAYER                1756
#define IDC_BT_FTP_SEND                 1757
#define IDC_BT_PASTE_LAYER              1757
#define IDC_BT_FILE_SEND                1758
#define IDC_ED_LAYER_NUM                1758
#define IDC_WAIT_TEXT                   1759
#define IDC_LAYER_LIST_BOX              1759
#define IDC_CHAT_LISTBOX                1760
#define IDC_VSB_LAYER_BOX               1760
#define IDC_NUM_PLAYERS                 1761
#define IDC_STC_LAYER_TOTAL             1761
#define IDC_CHAT_EDIT                   1762
#define IDC_SEND                        1763
#define IDC_STC_ASPECT_RATIO            1764
#define IDC_STC_KEYBOARD                1764
#define IDC_RB_4_3                      1765
#define IDC_RB_16_9                     1766
#define IDC_STC_STARTUP                 1766
#define IDC_STC_ITALIC_ANGLE            1767
#define IDC_CK_STYLE_SETTING            1767
#define IDC_RB_SQR_PIXEL                1768
#define IDC_CK_LAST_PROJECT             1768
#define IDC_STC_SMALL_CAP_HEIGHT        1769
#define IDC_CB_KEYBOARD                 1769
#define IDC_STC_SUPER_SIZE              1770
#define IDC_STC_SUPER_OFFSET            1771
#define IDC_STC_SUB_SIZE                1772
#define IDC_STC_PIC                     1772
#define IDC_STC_SUB_OFFSET              1773
#define IDC_STC_UNDERLN_SIZE            1774
#define IDC_STC_UNDERLNE_OFFSET         1775
#define IDC_VSB_WINBIN                  1775
#define IDC_STC_COLOR                   1776
#define IDC_STC_SUPERSCRIPT             1777
#define IDC_LST_BINWIN                  1777
#define IDC_STC_SUBSCRIPT               1778
#define IDC_BT_STOP_PLAY                1778
#define IDC_BT_PAL_PICKER               1778
#define IDC_STC_UNDERLINE               1779
#define IDC_FRM_C_PREVIEW               1779
#define IDC_ED_ITALIC_ANGLE             1780
#define IDC_STC_C_LENGTH                1780
#define IDC_ED_SUPER_SIZE               1781
#define IDC_ED_C_LENGTH                 1781
#define IDC_ED_SUPER_OFFSET             1782
#define IDC_SPN_C_LENGTH                1782
#define IDC_ED_SUB_SIZE                 1783
#define IDC_STC_C_THICK                 1783
#define IDC_ED_SUB_OFFSET               1784
#define IDC_ED_C_THICK                  1784
#define IDC_ED_UNDERLNE_SIZE            1785
#define IDC_SPN_C_THICK                 1785
#define IDC_ED_UNDERLNE_OFFSET          1786
#define IDC_STC_C_ROTATION              1786
#define IDC_ED_SMALL_CAP_HEIGHT         1787
#define IDC_ED_C_ROTATION               1787
#define IDC_SPN_ITALIC_ANGLE            1788
#define IDC_SPN_C_ROTATE                1788
#define IDC_SPN_SMALL_CAP_HEIGHT        1789
#define IDC_STC_C_VERTICES              1789
#define IDC_SPN_SUPER_SIZE              1790
#define IDC_ED_C_VERTICES               1790
#define IDC_SPN_SUPER_OFFSET            1791
#define IDC_SPN_C_VERTICES              1791
#define IDC_SPN_SUB_SIZE                1792
#define IDC_STC_C_ROUNDNESS             1792
#define IDC_SPN_SUB_OFFSET              1793
#define IDC_ED_C_ROUNDNESS              1793
#define IDC_SPN_UNDERLNE_SIZE           1794
#define IDC_SPN_C_ROUNDNESS             1794
#define IDC_SPN_UNDERLNE_OFFSET         1795
#define IDC_STC_C_BEVEL                 1795
#define IDC_BT_PALETTE                  1796
#define IDC_ED_C_BEVEL                  1796
#define IDC_BT_NEW_PAGE                 1797
#define IDC_SPN_C_BEVEL                 1797
#define IDC_BT_EXPORT_PAGE              1798
#define IDC_STC_C_X                     1798
#define IDC_GP_INDICATOR                1799
#define IDC_ED_C_X                      1799
#define IDC_CK_SAFE_TITLE               1800
#define IDC_SPN_C_X                     1800
#define IDC_STC_C_Y                     1801
#define IDC_ED_C_Y                      1802
#define IDC_SPN_C_Y                     1803
#define IDC_ED_C_PRIORITY               1804
#define IDC_SPN_C_PRIORITY              1805
#define IDC_BT_C_LOCK                   1806
#define IDC_BT_C_F                      1807
#define IDC_BT_C_PLUS                   1808
#define IDC_BT_C_MINUS                  1809
#define IDC_BT_C_B                      1810
#define IDC_FRM_P_PREVIEW               1811
#define IDC_STC_P_LENGTH                1812
#define IDC_ED_P_LENGTH                 1813
#define IDC_SPN_P_LENGTH                1814
#define IDC_STC_P_THICK                 1815
#define IDC_ED_P_THICK                  1816
#define IDC_SPN_P_THICK                 1817
#define IDC_SPN_P_VERTICES              1818
#define IDC_ED_P_VERTICES               1819
#define IDC_STC_P_VERTICES              1820
#define IDC_SPN_P_ROTATE                1821
#define IDC_ED_P_ROTATION               1822
#define IDC_STC_P_ROTATION              1823
#define IDC_SPN_P_BEVEL                 1824
#define IDC_ED_P_BEVEL                  1825
#define IDC_STC_P_BEVEL                 1826
#define IDC_SPN_P_ROUNDNESS             1827
#define IDC_ED_P_ROUNDNESS              1828
#define IDC_STC_P_ROUNDNESS             1829
#define IDC_SPN_P_Y                     1830
#define IDC_ED_P_Y                      1831
#define IDC_STC_P_Y                     1832
#define IDC_SPN_P_X                     1833
#define IDC_ED_P_X                      1834
#define IDC_STC_P_X                     1835
#define IDC_SPN_P_PRIORITY              1836
#define IDC_ED_P_PRIORITY               1837
#define IDC_BT_P_B                      1838
#define IDC_BT_P_MINUS                  1839
#define IDC_BT_P_PLUS                   1840
#define IDC_BT_P_F                      1841
#define IDC_BT_P_LOCK                   1842
#define IDC_CK_POLY_FILL                1844
#define IDC_ED_HEIGHT_PERCENT           1845
#define IDC_SPN_HEIGHT_PERCENT          1846
#define IDC_TXT_PRESET                  1857
#define IDC_GFX_PRESET                  1858
#define IDC_CK_FA_ENABLE                1858
#define IDC_SHOW_COLOR                  1859
#define IDC_SHOW_TEXTURE                1860
#define IDC_CK_CA_ENABLE                1860
#define IDC_CK_OL1_ENABLE               1861
#define IDC_CK_OL2_ENABLE               1862
#define IDC_CK_SD_ENABLE                1863
#define ID_PAGE_TYPE_STILL              32772
#define ID_PAGE_TYPE_ROLL               32773
#define ID_PAGE_TYPE_CRAWL              32774
#define ID_FORMAT_LFT                   32785
#define ID_FORMAT_CNT                   32786
#define ID_FORMAT_RIT                   32787
#define ID_FORMAT_JUT                   32788
#define ID_FORMAT_TOP                   32789
#define ID_FORMAT_MID                   32790
#define ID_FORMAT_BOT                   32791
#define ID_VIEW_PANEL_BAR               32792
#define ID_OPT_ONE                      32793
#define ID_OPT_TWO                      32794
#define ID_FORMAT_GRD                   32795
#define ID_TXTGFX_TEXT                  32796
#define ID_TXTGFX_LINE                  32797
#define ID_TXTGFX_BOX                   32801
#define ID_TXTGFX_OVAL                  32804
#define ID_TXTGFX_FILL                  32805
#define ID_TXTGFX_IMPORT                32807
#define ID_LOAD_MENU                    32808
#define ID_FORMAT_PTR                   32810
#define ID_FORMAT_PAL                   32811
#define ID_VDO_SET_UP                   32812
#define ID_PG_CUT                       32813
#define ID_PG_ADD_PIC                   32814
#define ID_PG_WORD_WRAP                 32815
#define ID_PG_CLEAR_ALL                 32816
#define ID_PG_CLEAR_TEXT                32817
#define ID_PG_CLEAR_GRAPHIC             32818
#define ID_PG_SPELL_CHECK               32819
#define ID_OPT_REDRAW                   32821
#define ID_REFRESH_PAGE                 32822
#define ID_REFRESH_ATT_FACE             32824
#define ID_REFRESH_ATT_OUTLINE1         32825
#define ID_REFRESH_ATT_OUTLINE2         32826
#define ID_REFRESH_ATT_SHADOW           32827
#define ID_REFRESH_ATT_CAST             32828
#define ID_REFRESH_EFFECT               32829
#define ID_REFRESH_ATT_TEXT             32830
#define ID_REFRESH_ATT_LINE             32831
#define ID_REFRESH_ATT_BOX              32832
#define ID_REFRESH_ATT_OVAL             32833
#define ID_REFRESH_ATT_FILL             32834
#define ID_REFRESH_CAPTURE              32835
#define ID_SET_TAB                      32837
#define ID_FORMAT_UNDO                  32843
#define ID_FORMAT_REDO                  32844
#define ID_FILE_TAB_SETUP               32845
#define ID_FILE_PREFERENCE              32847
#define ID_CLIP_COPY                    32849
#define ID_CLIP_PASTE                   32850
#define ID_FILE_IMPORT_TEXT             32852
#define ID_FILE_SCAN_IMAGE              32854
#define ID_FILE_SELECT_SCANNER          32855
#define ID_EDIT_CHAR_MAP                32856
#define ID_EDIT_FONT_LOCATOR            32857
#define ID_REFRESH_BASELINE             32859
#define ID_UNCHECK_ALPHA                32860
#define ID_FILE_EXPORT_PAGE             32862
#define ID_FILE_EXPORT_PROJECT          32863
#define ID_FILE_IMPORT_GFX              32864
#define ID_PAGE_CUT                     32866
#define ID_PAGE_COPY                    32867
#define ID_PAGE_PASTE                   32868
#define ID_TXTGFX_MAG                   32869
#define ID_TXTGFX_MAG_PLUS              32870
#define ID_TXTGFX_MAG_MINUS             32871
#define ID_HELP_TOPICS                  32872
#define ID_FILE_PROG_SETTING            32875
#define ID_LN_CLEAR                     32876
#define ID_LN_DELETE                    32877
#define ID_LN_INSERT_BEFORE             32878
#define ID_LN_INSERT_AFTER              32879
#define ID_LN_JUST_LEFT                 32880
#define ID_LN_JUST_CENTER               32881
#define ID_LN_JUST_RIGHT                32882
#define ID_LN_JUST_FLUSH                32883
#define ID_STYLE_COPY                   32884
#define ID_STYLE_PASTE                  32885
#define ID_STYLE_SAVE_TO_BIN            32886
#define ID_STYLE_RESET                  32887
#define ID_FKEY_F1                      32888
#define ID_FKEY_F2                      32889
#define ID_FKEY_F3                      32890
#define ID_FKEY_F4                      32891
#define ID_FKEY_F5                      32892
#define ID_FKEY_F6                      32893
#define ID_FKEY_F7                      32894
#define ID_FKEY_F8                      32895
#define ID_FKEY_F9                      32896
#define ID_FKEY_F10                     32897
#define ID_FKEY_F11                     32898
#define ID_FKEY_F12                     32899
#define IDM_POP_LAYER_0                 32903
#define IDM_POP_LAYER_1                 32904
#define IDM_POP_PAGE_0                  32905
#define IDM_POP_PAGE_1                  32906
#define IDM_POP_PAGE_OPT_0              32907
#define IDM_POP_PAGE_OPT_1              32908
#define IDM_POP_PAGE_OBJ_0              32909
#define IDM_POP_PAGE_OBJ_1              32910
#define IDM_POP_STYLE_BIN_0             32911
#define IDM_POP_STYLE_BIN_1             32912
#define IDM_POP_COLOR_BIN_0             32913
#define IDM_POP_COLOR_BIN_1             32914
#define ID_PAGE_PASTE_BEFORE            32915
#define ID_PAGE_PASTE_AFTER             32916
#define ID_PAGE_DUPLICATE               32917
#define ID_PAGE_IN_NEW_BEFORE           32918
#define ID_PAGE_IN_NEW_AFTER            32919
#define ID_PAGE_LEFT                    32920
#define ID_PAGE_CENTER                  32921
#define ID_PAGE_RIGHT                   32922
#define ID_PAGE_FLUSH                   32923
#define ID_ED_UNDO                      32924
#define ID_ED_REDO                      32925
#define ID_POS_PASTE                    32926
#define ID_TXTGFX_CURV                  32936
#define ID_TXTGFX_POLYGON               32937
#define ID_REFRESH_ATT_CURV             32938
#define ID_REFRESH_ATT_POLY             32939
#define ID_REFRESH_ATT_PIC              32940
#define ID_SET_PAGE_SCROLL_POS          32942
#define ID_SET_BIN_TOP_SCROLL_POS       32943
#define ID_SET_BIN_BOT_SCROLL_POS       32944
#define IDM_COMM_SENDER                 40008
#define IDM_COMM_RECEIVER               40009
#define IDM_HOST_FINDER                 40010
#define IDM_DOWNLOAD                    40011
#define IDM_MODEM                       40012
#define ID_FILE_MRU_PROJ1               0xE118
#define ID_FILE_MRU_PROJ2               0xE119
#define ID_FILE_MRU_PROJ3               0xE11A
#define ID_FILE_MRU_PROJ4               0xE11B
#define ID_FILE_MRU_PROJ5               0xE11C
#define ID_FILE_MRU_PROJ6               0xE11D
#define ID_FILE_MRU_PROJ7               0xE11E
#define ID_FILE_MRU_PROJ8               0xE11F
#define IDS_REG_KEY                     61216
#define IDS_FILTERSTRING                61217
#define IDS_DSMNAME                     61218
#define IDC_STC_NUM0                    65529
#define IDC_STC_NUM1                    65530
#define IDC_STC_NUM2                    65531
#define IDC_STC_NUM3                    65532
#define IDC_STC_NUM4                    65533
#define IDC_STC_NUM5                    65534
#define IDC_STC_VDO_FORMAT              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        363
#define _APS_NEXT_COMMAND_VALUE         32954
#define _APS_NEXT_CONTROL_VALUE         1864
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
