//ObjectTypes.h
#ifndef OBJECT_TYPES_H
#define OBJECT_TYPES_H

enum {TEXT_OBJ_SUBTYPE,BOX_OBJ_SUBTYPE,FULL_SCREEN_BACKGROUND_OBJ_SUBTYPE,PICTURE_OBJ_SUBTYPE,ELLIPSE_OBJ_SUBTYPE,LINE_OBJ_SUBTYPE,CURVE_OBJ_SUBTYPE,POLYGON_OBJ_SUBTYPE,UNDERLINE_OBJ_SUBTYPE,MAX_EDIT_OBJECT_SUBTYPES};

#endif	// OBJECT_TYPES_H
