[Tooltip]
IDD_PIC_LOAD_OPT	"Add Picture Options"
IDC_STC_FILE		"File"
IDC_STC_ORIG_SIZE	"Original Size"
IDC_GP_LD_SIZE		"Load Option"
IDC_RB_ORIG_SIZE	"Original Size"
IDC_RB_FIT_ED_WIN	"Fit to Edit Window"
IDC_STC_ED_WIN_SIZE 	"% edit window size"
IDC_CK_A_CH_INCLUDE 	"Include Alpha Channel"
IDC_CK_A_CH_INVERT  	"Invert Alpha Channel"
IDC_CK_BLACK_TRIM	"Black Trim"
IDC_GP_POSITION		"Position"
IDOK			"OK"
IDCANCEL		"Cancel"
end
