[Tooltip]
IDC_CB_FONT		"Font Selection"
IDC_RB_BOLD		"Bold"
IDC_RB_ITALIC		"Italic"
IDC_RB_UNDERLNE		"Underline"
IDC_FRM_PREVIEW		"Preview"
IDC_BT_LOCK		"Lock or Unlock"
IDC_BT_F		"Foreground"
IDC_BT_PLUS		"Forward"
IDC_BT_MINUS		"Backward"
IDC_BT_B		"Background"
IDC_ED_HEIGHT		"5..999"
IDC_ED_SPACE		"-64..+64"
IDC_ED_ROTATION		"0..359"
IDC_ED_WIDTH		"5..500"
IDC_ED_KERNING		"-64..+64"
IDC_ED_BEVEL		"0-32"
IDC_ED_PRIORITY		"0-255"
IDC_ED_X		"X position"
IDC_ED_Y		"Y position"
end  
