[Tooltip]
IDC_STC_SPEED		"Speed"
IDC_ED_MM		"0..90"
IDC_ED_SC		"0..60"
IDC_ED_FM		"0..29"
IDC_ED_SPD		"Speed"
IDC_ED_START_PG		"Starting Page"
IDC_ED_END_PG		"Ending Page"
IDC_BT_PLAY_PROJ	"Play Project"
IDC_BT_STOP_PLAY	"Stop Playback"
IDC_BT_TAKE		"Take"
IDC_BT_FADE_VDO		"Fade to video"
IDC_BT_LIVE_VDO		"Live Video"
IDC_CK_GPI		"GPI"
IDC_CK_LOOP		"LOOP"
IDC_RB_ALL_PAGE		"All Pages"
IDC_RB_PAGE		"Pages"
IDC_STC_HOLD_TIME	"Hold Time"
end 
