[Tooltip]
IDC_STC_OL_COLOR		"Color"
IDC_STC_OL_TRANS		"Transpancy"
IDC_BT_COL_IMP_OL		"Import"
IDC_BT_COL_PAL_OL		"Palette"
IDC_BT_TRANS_IMP_OL		"Import"
IDC_BT_TRANS_PAL_OL		"Palette"
IDC_BT_TRANS_ALPHA_OL		"Alpha"
IDC_ED_TRANS_OL			"Trnsparence 0..100"
IDC_ED_OL1_SIZE			"Size 0..99"
IDC_ED_OL1_FEATHER		"Feather 0..32"
IDC_ED_OL1_XOFFSET		"X offset -128..+128"
IDC_ED_OL1_YOFFSET		"Y offset -128..+128"
IDC_CK_OL1_ENABLE		"Outline 1 Enable"
end 
