[Text String]
IDC_GP_OBJECT		"Objects"
IDC_GP_VIEW		"View"
IDC_BT_PREV		"Previous"
IDC_BT_NEXT		"Next"
IDC_BT_SEL_ALL		"Select All"
IDC_BT_SEL_TEXT		"Select Text"
IDC_BT_SEL_GRAPHIC	"Select Graphic"
IDC_BT_UN_SEL_ALL	"Unselect All"
IDC_CK_SELECT		"Select"
IDC_CK_HIDE_SEL_OBJ	"Hide Selected Objects"
IDC_CK_HIDE_GRAPHIC_OBJ	"Hide Graphic Objects"
IDC_CK_HIDE_LAYER_OBJ	"Hide Other Layers"
IDC_CK_HIDE_TEXT_OBJ	"Hide Text Objects"
end
