//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by W:\shared\product\GXlateRC\GXlateRC.rc
//
#define IDS_LDESCRIPTION_BMP            1
#define IDS_LDESCRIPTION_JPG            2
#define IDS_LDESCRIPTION_PCX            3
#define IDS_LDESCRIPTION_TIF            4
#define IDS_LDESCRIPTION_PNG            5
#define IDS_LDESCRIPTION_IFF            6
#define IDS_LDESCRIPTION_TFS            7
#define IDS_LDESCRIPTION_TGA            8
#define IDS_LDESCRIPTION_AVI            9
#define IDS_LDESCRIPTION_MOV            10
#define IDS_LDESCRIPTION_MPG            11
#define IDS_SDESCRIPTION_BMP            12
#define IDS_SDESCRIPTION_JPG            13
#define IDS_SDESCRIPTION_PCX            14
#define IDS_SDESCRIPTION_TIF            15
#define IDS_SDESCRIPTION_PNG            16
#define IDS_SDESCRIPTION_IFF            17
#define IDS_SDESCRIPTION_TFS            18
#define IDS_SDESCRIPTION_TGA            19
#define IDS_SDESCRIPTION_AVI            20
#define IDS_SDESCRIPTION_MOV            21
#define IDS_SDESCRIPTION_MPG            22
#define IDS_LDESCRIPTION_PIC            23
#define IDS_SDESCRIPTION_PIC            24
#define IDS_LDESCRIPTION_PICT           25
#define IDS_SDESCRIPTION_PICT           26
#define IDS_LDESCRIPTION_PCT            27
#define IDS_SDESCRIPTION_PCT            28
#define IDS_LDESCRIPTION_GIF            29
#define IDS_SDESCRIPTION_GIF            30
#define IDS_LDESCRIPTION_WPG            31
#define IDS_SDESCRIPTION_WPG            32
#define IDS_LDESCRIPTION_WMF            33
#define IDS_SDESCRIPTION_WMF            34
#define IDS_LDESCRIPTION_SGI            35
#define IDS_SDESCRIPTION_SGI            36
#define IDS_LDESCRIPTION_PSD            37
#define IDS_SDESCRIPTION_PSD            38
#define IDS_LDESCRIPTION_RAS            39
#define IDS_SDESCRIPTION_RAS            40
#define IDS_FEXTENSIONS_BMP             41
#define IDS_FEXTENSIONS_JPG             42
#define IDS_FEXTENSIONS_PCX             43
#define IDS_FEXTENSIONS_TIF             44
#define IDS_FEXTENSIONS_PNG             45
#define IDS_FEXTENSIONS_IFF             46
#define IDS_FEXTENSIONS_TFS             47
#define IDS_FEXTENSIONS_TGA             48
#define IDS_FEXTENSIONS_AVI             49
#define IDS_FEXTENSIONS_MOV             50
#define IDS_FEXTENSIONS_MPG             51
#define IDS_FEXTENSIONS_PIC             52
#define IDS_FEXTENSIONS_PICT            53
#define IDS_FEXTENSIONS_PCT             54
#define IDS_FEXTENSIONS_GIF             55
#define IDS_FEXTENSIONS_WPG             56
#define IDS_FEXTENSIONS_WMF             57
#define IDS_FEXTENSIONS_SGI             58
#define IDS_FEXTENSIONS_PSD             59
#define IDS_FEXTENSIONS_RAS             60
#define IDS_UI_LDCS                     61
#define IDS_UI_EMM                      62
#define IDS_UI_TTI                      63
#define IDS_UI_TTCS                     64
#define IDS_UI_TTAN                     65
#define IDS_UI_GLL                      66
#define IDS_UI_CL                       67
#define IDS_UI_BDL                      68
#define IDS_UI_NL                       69
#define IDS_UI_P1_1                     70
#define IDS_UI_P1_2                     71
#define IDS_UI_P2                       72
#define IDS_UI_P3_1                     73
#define IDS_UI_P3_2                     74
#define IDS_UI_P3_3                     75
#define IDS_UI_P3_4                     76
#define IDS_UI_EXT_1                    77
#define IDS_UI_EXT_2                    78
#define IDS_UI_BLANK_FNAME              79
#define IDS_UI_CP_RED                   80
#define IDS_UI_CP_GREEN                 81
#define IDS_UI_CP_BLUE                  82
#define IDS_UI_CP_Y                     83
#define IDS_UI_CP_U                     84
#define IDS_UI_CP_V                     85
#define IDS_UI_CP_H                     86
#define IDS_UI_CP_S                     87
#define IDS_UI_CP_V2                    88
#define IDS_UI_CP_RGB                   89
#define IDS_UI_CP_YUV                   90
#define IDS_UI_CP_HSV                   91
#define IDS_UI_ALPHA                    92
#define IDS_UI_DEFCOL                   93
#define IDS_UI_PREVIEW_TEXT             94
#define IDS_LDESCRIPTION_EIM            95
#define IDS_LDESCRIPTION_TM             96
#define IDS_CE_TM_NTSC_1                97
#define IDS_CE_TM_NTSC_2                98
#define IDS_CE_TM_PAL_1                 99
#define IDS_CE_TM_PAL_2                 100
#define IDS_CE_PSD_NONE_1               101
#define IDS_CE_PSD_NONE_2               102
#define IDS_CE_PSD_RLE_1                103
#define IDS_CE_PSD_RLE_2                104
#define IDS_CE_PIC_NONE_1               105
#define IDS_CE_PIC_NONE_2               106
#define IDS_CE_PIC_RLE_1                107
#define IDS_CE_PIC_RLE_2                108
#define IDS_CE_PICT_NONE_1              109
#define IDS_CE_PICT_NONE_2              110
#define IDS_CE_PICT_RLE_1               111
#define IDS_CE_PICT_RLE_2               112
#define IDS_CE_RAS_NONE_1               113
#define IDS_CE_RAS_NONE_2               114
#define IDS_CE_RAS_RLE_1                115
#define IDS_CE_RAS_RLE_2                116
#define IDS_CE_SGI_NONE_1               117
#define IDS_CE_SGI_NONE_2               118
#define IDS_CE_SGI_RLE_1                119
#define IDS_CE_SGI_RLE_2                120
#define IDS_CE_EIM_NONE_1               121
#define IDS_CE_EIM_NONE_2               122
#define IDS_CE_EIM_RLE_1                123
#define IDS_CE_EIM_RLE_2                124
#define IDB_SPROCKETS                   125
#define IDB_SMALL_SPROCKETS             126
#define IDS_CE_PCT_NONE_1               127
#define IDS_CE_PCT_NONE_2               128
#define IDS_CE_PCT_RLE_1                129
#define IDS_CE_PCT_RLE_2                130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
