// ------------------------------------------------------------------------ //
// PlayLib.H
// Interface for PlayLib utility library
//
// Copyright @ 1999 Play Inc.
// Play Confidential
//
// Created on Aug 24, 1999 by Heman Gala
// ------------------------------------------------------------------------ //

// ------------------------------------------------------------------------- //
#ifndef __PlayLib_H__
#define __PlayLib_H__
// ------------------------------------------------------------------------- //

// Base headers
#include "PlayLib\PlayBaseTypes.H"		// Base type definitions
#include "PlayLib\PlayAdvTypes.H"		// Advanced type definitions
#include "PlayLib\PlayCallTypes.H"		// Call type definitions
#include "PlayLib\PlayStdDefines.H"		// Other standard definitions
#include "PlayLib\PlayDebug.H"			// Debug / Assert related defintions

// ClassLib headers
// --- Collection classes ---
#include "PlayLib\PlayList.H"
#include "PlayLib\PlayArray.H"

// --- COM Utility classes
#include "PlayLib\PlayUnknown.H"
#include "PlayLib\PlayClassFactory.H"

// ------------------------------------------------------------------------- //
#endif __PlayLib_H__
// ------------------------------------------------------------------------- //

// End-of-file : PlayLib.H
