//+---------------------------------------------------------------------------
//
//  Trinity Implementation
//  Copyright (C) Play Incorporated, 1996
//
//  File:       pubclsid.h
//
//  Contents:   Declaration of implementation CLSIDs for Trinity
//
//  History:    Feb 14, 1996 cmdaniel  created
//
//----------------------------------------------------------------------------
#ifndef __pubclsid_h__
#define __pubclsid_h__


extern const CLSID CLSID_CVideoSystem;          // Trinity Video System

extern const CLSID CLSID_CVidSystem;            // Simple Video 

extern const CLSID CLSID_CSimpleVid;            // Simple Video (new API)

extern const CLSID CLSID_CMediaManager;         // Media Manager

extern const CLSID CLSID_CEffectFile;           // Trinity Effect File class

#endif // __pubclsid_h__

// end of pubclsid.h
