//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PClient.rc
//
#define IDS_DIALOGFAILURE               6
#define IDS_STRUCTSIZE                  7
#define IDS_INITIALIZATION              8
#define IDS_NOTEMPLATE                  9
#define IDS_NOHINSTANCE                 14
#define IDS_LOADSTRFAILURE              15
#define IDS_FINDRESFAILURE              16
#define IDS_LOADRESFAILURE              17
#define IDS_LOCKRESFAILURE              18
#define IDS_MEMALLOCFAILURE             19
#define IDS_MEMLOCKFAILURE              20
#define IDS_NOHOOK                      21
#define IDS_SETUPFAILURE                22
#define IDS_PARSEFAILURE                23
#define IDS_RETDEFFAILURE               24
#define IDS_LOADDRVFAILURE              25
#define IDS_GETDEVMODEFAIL              26
#define IDS_INITFAILURE                 27
#define IDS_NODEVICES                   28
#define IDS_NODEFAULTPRN                29
#define IDS_DNDMMISMATCH                30
#define IDS_CREATEICFAILURE             31
#define IDS_PRINTERNOTFOUND             32
#define IDS_NOFONTS                     33
#define IDS_SUBCLASSFAILURE             34
#define IDS_INVALIDFILENAME             35
#define IDS_BUFFERTOOSMALL              36
#define IDS_FILTERSTRING                37
#define IDS_UNKNOWNERROR                38
#define IDD_EFFECTS_DIALOG              104
#define IDD_EFFECTS_PICON_DIALOG        105
#define IDD_CANCELDLG                   106
#define IDD_CAPTURE_DIALOG              107
#define IDD_CAPTURE_PICONS_DIALOG       108
#define IDD_VIDEO_SETUP_DIALOG          109
#define IDD_PAGEPANEL_DIALOG            113
#define IDB_1                           121
#define IDB_2                           122
#define IDB_3                           123
#define IDB_4                           124
#define IDB_5                           125
#define IDD_TEXT_PANEL_DIALOG           127
#define IDD_VIDEO_CLIP_DLG              128
#define IDD_VIDEO_FRAME_DLG             129
#define IDB_VDO_TEST                    130
#define IDC_CURSOR1                     131
#define IDC_CURSOR2                     133
#define IDB_TEST                        134
#define IDI_FACE                        171
#define IDD_POPUP_DLG                   239
#define IDD_MUL_MSG_DLG                 243
#define IDC_FX_PICON_PIC                1003
#define IDC_FX_PIC_LABEL                1004
#define IDC_HOLDTIME_LABEL              1005
#define IDC_SPEED_LABEL                 1006
#define IDC_GPI_CHECKBOX                1007
#define IDC_LOOP_CHECKBOX               1008
#define IDC_HOLDTIME_EDIT               1009
#define IDC_HOLDTIME_MIN_EDIT           1009
#define IDC_SPEED_EDITBOX               1010
#define IDC_CUTOUT_BUTTON               1011
#define IDC_PLAYPROJECT_BUTTON          1012
#define IDC_ALL_PAGES_RADIO             1013
#define IDC_PAGE_STATIC_STRING          1014
#define IDC_RANGE_RADIO                 1014
#define IDC_CURRENT_PAGE_EDIT           1015
#define IDC_BEGIN_RANGE_EDIT            1015
#define IDC_OF_STATIC_STRING            1016
#define IDC_END_RANGE_EDIT              1016
#define IDC_TOTAL_PAGES_STRING          1017
#define IDC_TO_TEXT                     1017
#define IDC_PLAYCURRENT_BUTTON          1018
#define IDC_PAGE_TYPE_COMBO             1019
#define IDC_FADEOUT_BUTTON              1019
#define IDC_PAGE_EXPORT_BUTTON          1020
#define IDC_ACG_LOGO_PIC                1021
#define IDS_STILL_STRING                1021
#define IDS_ROLL_STRING                 1022
#define IDS_CRAWL_STRING                1023
#define IDC_ROLLEND_TYPE_COMBO          1023
#define IDC_ROLLEND_LABEL               1024
#define IDC_FADE_ON_CHECK               1025
#define IDC_FADE_OFF_CHECK              1026
#define IDC_EFXCLOSE_BUTTON             1027
#define IDS_ONSCREEN_STRING             1028
#define IDC_HOLDTIME_SEC_EDIT           1028
#define IDS_OFFSCREEN_STRING            1029
#define IDC_HOLDTIME_FRAME_EDIT         1029
#define IDC_TAKE_BUTTON                 1030
#define IDC_CAPTURE_PIC                 1041
#define IDC_CAPTURE_EXPORT_BUTTON       1042
#define IDC_CAPTURE_TO_DISK_RADIO       1043
#define IDC_CAPTURE_TO_CG_RADIO         1044
#define IDC_CAPTURE_OK_BUTTON           1045
#define IDC_CAPTURE_TYPE_STATIC         1047
#define IDC_CAPTURE_TYPE_COMBO          1049
#define IDC_CAPTURE_RATE_STATIC         1050
#define IDC_CAPTURE_RATE_EDIT           1051
#define IDC_CAPTURE_RATE_SPIN           1052
#define IDC_GRAB_BUTTON                 1053
#define IDC_MULTI_GRAB_BUTTON           1054
#define IDC_VIDEO_INPUT_STATIC          1055
#define IDC_VIDEO_OUTPUT_STATIC         1056
#define IDC_VIDEO_BRIGHTNESS_STATIC     1057
#define IDC_VIDEO_BRIGHTNESS_EDIT       1058
#define IDC_VIDEO_BRIGHTNESS_SPIN       1059
#define IDC_VIDEO_BRIGHTNESS_SLIDER     1060
#define IDC_VIDEO_CONTRAST_STATIC       1061
#define IDC_VIDEO_CONTRAST_EDIT         1062
#define IDC_VIDEO_CONTRAST_SPIN         1063
#define IDC_VIDEO_CONTRAST_SLIDER       1064
#define IDC_VIDEO_HUE_STATIC            1065
#define IDC_VIDEO_HUE_EDIT              1066
#define IDC_VIDEO_HUE_SPIN              1067
#define IDC_VIDEO_HUE_SLIDER            1068
#define IDC_VIDEO_FLICKER_FILTER_CHECK  1069
#define IDC_VIDEO_NTSC_RADIO            1070
#define IDC_VIDEO_PAL_RADIO             1071
#define IDC_VIDEO_DEFAULTS_BUTTON       1074
#define IDS_COMMON_OK_STRING            1075
#define IDC_VIDEO_SETUP_OK_BUTTON       1075
#define IDS_COMMON_CANCEL_STRING        1076
#define IDC_TEXT_GROUPBOX               1078
#define IDC_LINEAR_RADIO                1079
#define IDC_CIRCULAR_RADIO              1080
#define IDC_SELECT_FONT_COMBO           1081
#define IDS_BOLD_TIPS                   1081
#define IDC_SIZE_STATIC                 1082
#define IDC_FONTSIZE_EDIT               1083
#define IDS_ITALIC_TIPS                 1083
#define IDC_WIDTH_STATIC                1084
#define IDC_FONTWIDTH_EDIT              1085
#define IDS_UNDERLINE_TIPS              1085
#define IDS_LINEAR_TEXT_TIPS            1086
#define IDC_BOLD_CHECK                  1087
#define IDC_ITALIC_CHECK                1088
#define IDC_UNDERLINE_CHECK             1089
#define IDS_CIRCULAR_TEXT_TIPS          1090
#define IDC_FONTSIZE_SPIN               1091
#define IDS_KERNING_PLUS_TIPS           1091
#define IDC_FONTWIDTH_SPIN              1092
#define IDS_KERNING_MINUS_TIPS          1092
#define IDC_SPACING_STATIC              1093
#define IDC_SPACING_EDIT                1094
#define IDS_PREVIEW_PIC                 1094
#define IDC_KERNING_STATIC              1095
#define IDS_LOCK_ATTRIBUTES_TIPS        1096
#define IDS_SELECT_FONT_TIPS            1097
#define IDC_KERNING_PLUS_BUTTON         1098
#define IDC_KERNING_MINUS_BUTTON        1099
#define IDC_FONTSPACING_SPIN            1100
#define IDC_FONT_PIC                    1102
#define IDC_LOCK_ATTRIBUTES_CHECK       1103
#define IDC_ATTRIBUTES_GROUPBOX         1104
#define IDC_LOAD_CLIP                   1105
#define IDC_ED_FILE_NAME                1106
#define IDC_PLAY_TITLE                  1107
#define IDC_PLAY                        1108
#define IDC_STOP                        1109
#define IDC_VDO_MON                     1114
#define IDC_APPLY_TITLE                 1115
#define IDC_OUT_FRAME                   1116
#define IDC_IN_FRAME                    1117
#define IDC_ED_IN_POINT                 1120
#define IDC_ED_OUT_POINT                1121
#define IDC_HS_IN_POINT                 1122
#define IDC_HS_OUT_POINT                1123
#define IDC_ED_DURATION                 1125
#define IDC_ED_OUT_HH                   1126
#define IDC_ED_OUT_MM                   1127
#define IDC_ED_OUT_SS                   1128
#define IDC_ED_OUT_FF                   1129
#define IDC_ED_IN_HH                    1130
#define IDC_ED_IN_MM                    1131
#define IDC_ED_IN_SS                    1132
#define IDC_ED_IN_FF                    1133
#define IDC_OUT_RECT                    1134
#define IDC_ED_TO_HH                    1134
#define IDC_ED_TO_MM                    1135
#define IDC_IN_RECT                     1135
#define IDC_ED_TO_FF                    1137
#define IDC_ED_FR_HH                    1138
#define IDC_ED_FR_MM                    1139
#define IDC_ED_FR_SS                    1140
#define IDC_ED_FR_FF                    1141
#define IDC_ED_TO_SS                    1142
#define IDC_BUT1                        1142
#define IDC_SPD_SPIN                    1144
#define IDC_VDO_IN_FORMAT               1145
#define IDC_VDO_OUT_FORMAT              1146
#define IDC_POPUP_MSG                   1236
#define IDC_POPUP_ICON                  1237
#define IDC_BUT2                        1241
#define IDC_BUT3                        1242
#define IDS_STOPPLAY_STRING             5909
#define IDS_PRESETS_TAB_STRING          5910
#define IDS_EFFECTS_TAB_STRING          5911
#define IDS_CAPTURE_TAB_STRING          5912
#define IDS_PAGES_TAB_STRING            5913
#define IDS_LAYERS_TAB_STRING           5914
#define IDS_BOTH_FIELDS_STRING          5915
#define IDS_EVEN_FIELD_STRING           5916
#define IDS_ODD_FIELD_STRING            5917
#define IDS_INTERPOLATED_FRAME_STRING   5918
#define IDS_EXPORT_DIALOG_TITLE_STRING  5919
#define IDS_RANGE_RADIO_STRING          5920
#define IDS_VIDEO_SETUP_TITLE_STRING    5921
#define IDS_VIDEO_SETTINGS_FORMAT_CHANGED_STRING 5922
#define IDS_VIDEO_SETTINGS_FORMAT_CHANGED_CAPTION_STRING 5923
#define IDS_TIPS_NEWPROJECT             5924
#define IDS_VIDEO_CLIP_TAB              5924
#define IDS_TIPS_OPENPROJECT            5925
#define IDS_TIPS_SAVEPROJECT            5926
#define IDS_TIPS_ADDPICTURE             5927
#define IDS_TIPS_ABOUT                  5928
#define IDM_CLIPBOARD_PASTE_GFX         40002
#define IDM_CLIPBOARD_COPY_GRAPHICS     40003
#define IDM_CLIPBOARD_PASTE_TEXT        40004
#define IDM_CLIPBOARD_COPY_TEXT         40005
#define IDM_PRINT_PAGE                  40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
